### ISSUE TITLE
Switch rendering order not working

### ISSUE THREAD

**Issue by GuineaThePig** [bluesatin/foundry-vtt-layers-panel#17]
As far as I can tell the 'Switch rendering order of drawings and tiles' option doesn't do anything in 8.6.

No matter what any non-overhead tiles are placed under drawings

**Comment by bluesatin** [comment]
I need to get around to checking things on FoundryVTT 8.6, I haven't had a chance to mess around with it yet.

I was kinda expecting everything to break, but glad to hear it's not completely borked!

The issue might is likely related to all the stuff with overhead tiles etc. changing a few things behind the scenes. The switch rendering order option hooks onto the `canvas.tiles` / `canvas.drawings` layers that have likely had some changes, I'll try to get around to checking it at some point during the week.

Is the option completely breaking anything? Or is it just not functioning at all.

**Comment by GuineaThePig** [comment]
As far as I can tell nothing is breaking, it just does nothing. Everything else is working fine it seems, though I also just started messing around with 8.6 so I might be missing something.

**Comment by bluesatin** [comment]
Ah looks like it's likely that the `canvas.tiles` layer has been split into 2 different ones, and that's causing the issue:

>Tiles layer has been split into two, Underfoot and Overhead, so tokens can stay below the overhead ones, allowing the creation of tree canopies, bridges, hanging vines, etc.

Hopefully it's just a case of switching out a couple of things to reference the new layers.

Thanks for the report!

If there's any other issues or small annoyances you spot, let me know with some new issues. :)

**Comment by bluesatin** [comment]
Should be fixed in 0.2.1, although I haven't done extensive testing with the background/foreground layers stuff.
